spring:
  server-url:
    base: ENC(eAV32/4c9hWU0yc8LNmFBlmzx1+M2uZ50FKV9xuYkdU=)
  devtools:
    restart:
      enabled: false  # 자동 재시작 비활성화
    livereload:
      enabled: true   # 라이브 리로드는 활성화 (브라우저 자동 새로고침)
  datasource:
    username: ENC(q8ROcg0aSk0+mMm8MviPmU5B1jxCr1DX)
    password: ENC(OCkIFLb6xuMuwCt22KuBtw6azkYiTPe+)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(u7VcHyIyZt5FttG/AHlNyDu5LVkRVdUQVtweFO+rL21FCXJfV8SUOhF3wi8xRQ6q3CTSXwySlUw=)
  jpa:
    show-sql: false
    open-in-view: false
  data:
    mongodb:
      database: musicSNS
      host: ENC(ufmawWcznlhmCpk3nUDjdBCHmJkh8O+l)
    redis:
      host: ENC(AzgYou82XYFiA4K5vEtBy4HsDR9akT1T)
      port: 6379
      timeout: 3000