spring:
  server-url:
    base: ENC(eAV32/4c9hWU0yc8LNmFBlmzx1+M2uZ50FKV9xuYkdU=)
  devtools:
    restart:
      enabled: false  # 자동 재시작 비활성화
    livereload:
      enabled: true   # 라이브 리로드는 활성화 (브라우저 자동 새로고침)
  datasource:
    username: ENC(1ss9Mwm1I0B4/RuwjsG2eQ==)
    password: ENC(V0JftcIy3PCcIuOsgJgj5IK1mbU7pHgw)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(W+Mp8/OgwHEJfGScuqOm6+Yx3V9wEt0oIyiaVDrkuajv5VHxi1ihXfTO8bKN0ZR2vpwqDrHXxEo=)
  jpa:
    show-sql: false
    open-in-view: false
  data:
    mongodb:
      database: musicSNS
      host: ENC(utFmuG8gQCYugSiaq7yhJ0I5AT+PkBR9)
      username: ENC(+8nfaF0A1XK6uwsY7ca1iA==)
      password: ENC(ZU27Z6PcHdFWATgWTSHWYXucfW5kNyHh)
      authentication-database: ENC(/+zSKs+A0kvJV+AVV6gFjA==)
    redis:
      host: ENC(AzgYou82XYFiA4K5vEtBy4HsDR9akT1T)
      port: 6379
      timeout: 3000